export const USERS_BBDD =[
    {
      "_id": "65ad066d22521e9ab09a277b",
      "index": 0,
      "guid": "39424d46-bae2-4659-b3ce-3256f34497a4",
      "isActive": true,
      "balance": "$3,949.39",
      "picture": "http://placehold.it/32x32",
      "age": 37,
      "eyeColor": "brown",
      "name": "Annabelle Cross",
      "gender": "female",
      "company": "INSECTUS",
      "email": "annabellecross@insectus.com",
      "phone": "+1 (878) 466-2344",
      "address": "943 Madison Place, Sims, New Mexico, 3857",
      "about": "Pariatur est ex amet dolore culpa ullamco quis cupidatat ea reprehenderit incididunt eu. Eu eu veniam nostrud sunt veniam sunt nisi esse magna consequat. Laborum in est sunt deserunt consectetur ullamco aliqua mollit culpa. Ad consectetur id eu tempor minim.\r\n",
      "registered": "2015-09-20T01:54:51 +03:00"
    },
    {
      "_id": "65ad066d34f5fe3f2c4b7aab",
      "index": 1,
      "guid": "a9bc43dd-a778-4ee8-b3a4-7ce7ce7ec68a",
      "isActive": false,
      "balance": "$3,419.56",
      "picture": "http://placehold.it/32x32",
      "age": 38,
      "eyeColor": "blue",
      "name": "Pauline Charles",
      "gender": "female",
      "company": "APPLIDECK",
      "email": "paulinecharles@applideck.com",
      "phone": "+1 (932) 559-3036",
      "address": "789 Senator Street, Nanafalia, California, 509",
      "about": "Laboris esse enim veniam elit id anim. Qui culpa consequat anim occaecat eu eiusmod amet consectetur et ea deserunt exercitation tempor qui. Eiusmod deserunt commodo qui eiusmod elit proident.\r\n",
      "registered": "2020-08-10T03:07:46 +03:00"
    },
    {
      "_id": "65ad066dec0e3526506a7488",
      "index": 2,
      "guid": "5eda0723-7411-45a6-bde0-0913206c6bc4",
      "isActive": false,
      "balance": "$3,299.26",
      "picture": "http://placehold.it/32x32",
      "age": 39,
      "eyeColor": "brown",
      "name": "Josefina Cox",
      "gender": "female",
      "company": "COWTOWN",
      "email": "josefinacox@cowtown.com",
      "phone": "+1 (958) 403-3396",
      "address": "211 Adelphi Street, Duryea, New Hampshire, 9097",
      "about": "Nulla Lorem labore exercitation ea. Magna deserunt duis nisi nisi. Eiusmod id laboris qui pariatur fugiat ad Lorem. Commodo ea dolore sunt adipisicing laboris nisi consequat laborum. Tempor nulla quis ad labore pariatur quis elit ut esse velit. Consectetur aliqua consectetur dolore deserunt dolor labore. Mollit magna reprehenderit excepteur nostrud aliquip laboris eiusmod incididunt officia sint et.\r\n",
      "registered": "2020-07-30T06:04:04 +03:00"
    },
    {
      "_id": "65ad066d8b11bbe3ff1593ee",
      "index": 3,
      "guid": "7355fa05-74eb-48b4-87e7-9890486fab72",
      "isActive": false,
      "balance": "$3,712.84",
      "picture": "http://placehold.it/32x32",
      "age": 20,
      "eyeColor": "brown",
      "name": "Clarice Turner",
      "gender": "female",
      "company": "ZEROLOGY",
      "email": "clariceturner@zerology.com",
      "phone": "+1 (914) 437-2881",
      "address": "640 Provost Street, Connerton, Northern Mariana Islands, 5998",
      "about": "Consectetur nulla exercitation quis incididunt magna id culpa id ut incididunt in qui cillum. Do esse nulla exercitation deserunt ex minim. Veniam fugiat cillum laboris exercitation ullamco do consectetur quis dolor velit. Mollit sit laborum irure dolore nulla exercitation mollit tempor qui cupidatat labore Lorem deserunt.\r\n",
      "registered": "2015-10-10T09:04:53 +03:00"
    },
    {
      "_id": "65ad066dd748714fde3e515e",
      "index": 4,
      "guid": "c9c8795c-00c4-46cc-9824-3077309d4258",
      "isActive": false,
      "balance": "$2,520.52",
      "picture": "http://placehold.it/32x32",
      "age": 23,
      "eyeColor": "blue",
      "name": "Patrick Abbott",
      "gender": "male",
      "company": "BIOTICA",
      "email": "patrickabbott@biotica.com",
      "phone": "+1 (901) 595-2298",
      "address": "868 Sullivan Street, Alamo, District Of Columbia, 712",
      "about": "Amet pariatur et amet veniam aliqua ea deserunt enim aliqua. Eu anim sunt amet deserunt. Nulla aliqua adipisicing nisi aute anim esse.\r\n",
      "registered": "2020-04-02T06:44:27 +03:00"
    }
  ]